[package]
name = "crop-and-edit"
version = "0.1.0"
description = "A simple powerful crop separation editor"
authors = ["Crop and Edit"]
edition = "2021"

[lib]
name = "crop_and_edit_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
image = { version = "0.25", default-features = false, features = ["bmp", "gif", "ico", "jpeg", "png", "qoi", "tga", "tiff", "webp"] }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
